#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : django_compressor
Version  : 1.5
Release  : 8
URL      : https://pypi.python.org/packages/source/d/django_compressor/django_compressor-1.5.tar.gz
Source0  : https://pypi.python.org/packages/source/d/django_compressor/django_compressor-1.5.tar.gz
Summary  : Compresses linked and inline JavaScript or CSS into single cached files.
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: django_compressor-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Django Compressor
=================
.. image:: https://coveralls.io/repos/django-compressor/django-compressor/badge.png?branch=develop
:target: https://coveralls.io/r/django-compressor/django-compressor?branch=develop

%package python
Summary: python components for the django_compressor package.
Group: Default

%description python
python components for the django_compressor package.


%prep
%setup -q -n django_compressor-1.5

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
