#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : django_compressor
Version  : 2.1.1
Release  : 24
URL      : http://pypi.debian.net/django_compressor/django_compressor-2.1.1.tar.gz
Source0  : http://pypi.debian.net/django_compressor/django_compressor-2.1.1.tar.gz
Summary  : Compresses linked and inline JavaScript or CSS into single cached files.
Group    : Development/Tools
License  : MIT NCSA
Requires: django_compressor-python
Requires: django-appconf
Requires: rcssmin
Requires: rjsmin
BuildRequires : django-appconf
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : rcssmin
BuildRequires : rjsmin
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
=================

%package python
Summary: python components for the django_compressor package.
Group: Default

%description python
python components for the django_compressor package.


%prep
%setup -q -n django_compressor-2.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1503087359
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1503087359
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
